### ISSUE TITLE
Is there a init method?? or should we use features for that part?!

### ISSUE THREAD

**Issue by kakarot-dev** [CreativeDevelopments/CDCommands#22]

**Comment by Maxisthemoose** [comment]
init method for what

**Comment by kakarot-dev** [comment]
for commands

**Comment by Maxisthemoose** [comment]
what do you mean

**Comment by Maxisthemoose** [comment]
The commands are loaded when you run your project

**Comment by kakarot-dev** [comment]
https://github.com/AlexzanderFlores/WOKCommands#command-initialization-method
like it will run a little bit of code when the bot starts up

**Comment by Maxisthemoose** [comment]
No, as of now, there is no code that runs in the command when the bot starts, I guess you could use a feature for that, but if you want us to add that we could

**Comment by kakarot-dev** [comment]
yes please add it

**Comment by kakarot-dev** [comment]
If I just use the template of the message event as it is, 
Will there be any errors?

**Comment by Exxonnnnnn** [comment]
> If I just use the template of the message event as it is,
> Will there be any errors?

Providing you use the one from Sourcebin rather than the GitHub one then yes it will work without any errors. You can get the template message.json from [here, on Sourcebin](https://sourceb.in/XpAciGMZsM)

**Comment by Maxisthemoose** [comment]
@kakarot-dev working on it now #23

**Comment by kakarot-dev** [comment]
Cool ThNks

**Comment by kakarot-dev** [comment]
> > If I just use the template of the message event as it is,
> > Will there be any errors?
> 
> Providing you use the one from Sourcebin rather than the GitHub one then yes it will work without any errors. You can get the template message.json from [here, on Sourcebin](https://sourceb.in/XpAciGMZsM)

Also is this updated while new features are added?

**Comment by Exxonnnnnn** [comment]
If you are talking about the message.js on Sourcebin yes it is updated. When I update it there will be a new link and it will be put on the readme under "Creating an Event".

**Comment by kakarot-dev** [comment]
Oki coolsies
